In [1]:
print('hello world')

hello world


In [1]:
import tensorflow as tf
tensor_zero_d = tf.constant(4)

In [2]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,4,3])
tensor_one_d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 0, 4, 3])>

In [4]:
tensor_two_d = tf.constant([
    [2,4,6],
    [1,5,6]
])
tensor_two_d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 4, 6],
       [1, 5, 6]])>

In [5]:
tensor_three_d = tf.constant([
    [[1,2,3],
     [1,2,3]],
    [[4,5,6],
     [6,7,8]]
])
tensor_three_d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [6, 7, 8]]])>

In [6]:
tensor = tf.cast(tensor_three_d,dtype = tf.int8)
print(tensor)

tf.Tensor(
[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [6 7 8]]], shape=(2, 2, 3), dtype=int8)


np arry to tensor

In [7]:
import numpy as np
arr = np.array([5,6,7,8])

In [8]:
tensor = tf.convert_to_tensor(arr)
print(tensor)

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)


In [12]:
identity = tf.eye(3,3,dtype = tf.dtypes.int8)
print(identity)

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int8)


In [13]:
print(tf.cast(identity,dtype=tf.bool))

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [15]:
with tf.device('GPU:0'):
    x_var = tf.Variable(0.2)
print(x_var.device)

/job:localhost/replica:0/task:0/device:GPU:0
